CREATE TABLE EMPLOYEE (
    EMP_NO INT PRIMARY KEY,
    ENAME VARCHAR(50) NOT NULL,
    JOB VARCHAR(50) NOT NULL,
    MGR INT,
    HIREDATE DATE NOT NULL,
    SAL DECIMAL(10, 2) NOT NULL,
    COMM DECIMAL(10, 2) NOT NULL,
    DEPT_NO INT NOT NULL,
    FOREIGN KEY (MGR)
);

CREATE TABLE DEPARTMENT (
    DEPRT_NO INT PRIMARY KEY,
    DNAME VARCHAR(50) NOT NULL,
    LOC VARCHAR(50) NOT NULL
);

INSERT INTO EMPLOYEE (EMP_NO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPT_NO) VALUES
(7839, 'KING', 'PRESIDENT', NULL, '1981-11-17', 5000.00, NULL, 10),
(7566, 'JONES', 'MANAGER', 7839, '1981-04-02', 2975.00, NULL, 20),
(7698, 'BLAKE', 'MANAGER', 7839, '1981-05-01', 2850.00, NULL, 30),
(7782, 'CLARK', 'MANAGER', 7839, '1981-06-09', 2450.00, NULL, 10),
(7788, 'SCOTT', 'ANALYST', 7566, '1982-12-09', 3000.00, NULL, 20),
(7902, 'FORD', 'ANALYST', 7566, '1981-12-05', 3000.00, NULL, 20),
(7844, 'TURNER', 'SALESMAN', 7698, '1981-09-08', 1500.00, 0.00, 30),
(7876, 'ADAMS', 'CLERK', 7788, '1983-01-12', 1100.00, NULL, 20),
(7900, 'JAMES', 'CLERK', 7698, '1981-06-13', 950.00, NULL, 30),
(7654, 'MARTIN', 'SALESMAN', 7698, '1981-09-28', 1250.00, 1400.00, 30),
(7499, 'ALLEN', 'SALESMAN', 7698, '1981-02-20', 1600.00, 300.00, 30),
(7521, 'WARD', 'SALESMAN', 7698, '1981-02-22', 1250.00, 500.00, 30),
(7934, 'MILLER', 'CLERK', 7782, '1982-01-21', 1300.00, NULL, 10);

-- TASK NO.1 --
SELECT ENAME, SAL
FROM EMPLOYEE
WHERE SAL > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'ALLEN');

-- TASK NO.2 --
SELECT * FROM EMPLOYEE
WHERE JOB = (SELECT JOB FROM
EMPLOYEE WHERE ENAME = 'MILLER');

-- TASK NO.3 --
SELECT ENAME, SAL
FROM EMPLOYEE
WHERE SAL > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'ADAMS');

-- TASK NO.4 --
SELECT ENAME, SAL
FROM EMPLOYEE
WHERE SAL < (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'KING');

-- TASK NO.5 --
SELECT ENAME, DEPRT_NO
FROM EMPLOYEE
WHERE DEPRT_NO = (SELECT DEPRT_NO FROM EMPLOYEE WHERE ENAME = 'JONES');

-- TASK NO.6 --
SELECT ENAME JOB
FROM EMPLOYEE
WHERE JOB = (SELECT JOB FROM EMPLOYEE WHERE ENAME = 'JAMES');

-- TASK NO.7 --
SELECT EMP_ID, ENAME, SAL * 12 AS ANNUAL_SALARY
FROM EMPLOYEE
WHERE (SAL * 12) > (SELECT SAL * 12 FROM EMPLOYEE WHERE ENAME = 'WARD');

-- TASK NO.8 --
SELECT ENAME, HIREDATE
FROM EMPLOYEE
WHERE HIREDATE < (SELECT HIREDATE FROM EMPLOYEE WHERE ENAME = 'TURNER');

--TASK NO.9 --
SELECT ENAME, HIREDATE
FROM EMPLOYEE
WHERE HIREDATE > (SELECT HIREDATE FROM EMPLOYEE WHERE ENAME = 'KING');

-- TASK NO.10 --
SELECT ENAME, SAL
FROM EMPLOYEE
WHERE SAL < (SELECT SAL FROM EMPLOYEE WHERE EMP_ID = '7839');

-- TASK NO.11 --
SELECT * FROM EMPLOYEE
WHERE HIREDATE < (SELECT HIREDATE FROM EMPLOYEE WHERE ENAME = 'MILLER');

-- TASK NO.12 --
SELECT ENAME, DEPRT_NO
FROM EMPLOYEE
WHERE SAL > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'ALLAN');

-- TASK NO.13 --
SELECT ENAME, SAL
FROM EMPLOYEE
WHERE SAL > (SELECT SAL FROM EMPLOYEE WHERE ENAME  = 'SCOTT') AND
HIREDATE < (SELECT HIREDATE FROM EMPLOYEE ENAME = 'KING');

-- TASK NO.14 --
SELECT * FROM EMPLOYEE
WHERE JOB = (SELECT JOB FROM EMPLOYEE WHERE ENAME = 'TURNER') AND
SAL < 5000;

-- TASK NO.15 --
SELECT ENAME, SAL
FROM EMPLOYEE
WHERE SAL > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'MILLER') AND
SAL < (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'ALLAN');

-- TASK NO.16 --
SELECT * FROM EMPLOYEE
WHERE DEPRT_NO = 20 AND
JOB = (SELECT JOB FROM EMPLOYEE WHERE ENAME  = 'SMITH');

-- TASK NO.17 --
SELECT * FROM EMPLOYEE
WHERE JOB = 'MANAGER' AND
DEPRT_NO = (SELECT DEPRT_NO FROM EMPLOYEE WHERE ENAME = 'TURNER');

-- TASK NO.18 --
SELECT ENAME, HIREDATE
FROM EMPLOYEE
WHERE HIREDATE > '1980-01-01' AND
HIREDATE < (SELECT HIREDATE FROM EMPLOYEE WHERE ENAME = 'KING');

-- TASK NO.19 --
SELECT ENAME, SAL * 12 AS ANNUAL_SALARY
FROM EMPLOYEE
WHERE SAL < (SELECT SAL FROM EMPLOYEE WHERE ENAME  = 'BLAKE') AND
SAL > 3500;

-- TASK NO.20 --
SELECT * FROM EMPLOYEE
WHERE SAL > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'SCOTT') AND
SAL < (SELECT SAL FROM EMPLOYEE WHERE ENAME  = 'KING');

-- TASK NO.21 --
SELECT ENAME
FROM EMPLOYEE
WHERE ENAME LIKE 'A%' AND
DEPRT_NO = (SELECT DEPRT_NO FROM EMPLOYEE WHERE ENAME = 'BLAKE');

-- TASK NO.22 --
SELECT ENAME, COMM
FROM EMPLOYEE
WHERE COMM IS NOT NULL AND
JOB = (SELECT JOB FROM EMPLOYEE WHERE ENAME = 'SMITH');

-- TASK NO.23 --
SELECT * FROM EMPLOYEE
WHERE JOB = 'CLERK' AND
DEPRT_NO = (SELECT DEPRT_NO FROM EMPLOYEE WHERE ENAME = 'TURNER');

-- TASK NO.24 --
SELECT ENAME, SAL, JOB
FROM EMPLOYEE
WHERE SAL * 12 > (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'SMITH') AND
SAL * 12 < (SELECT SAL FROM EMPLOYEE WHERE ENAME = 'KING');

-- TASK NO.25 --
SELECT DISTINCT SAL
FROM EMPLOYEE
ORDER BY SAL DESC
LIMIT 1 OFFSET 2;

-- TASK NO.26 --
SELECT ENAME
FROM EMPLOYEE
WHERE SAL = (SELECT DISTINCT SAL FROM EMPLOYEE ORDER BY SAL ASC LIMIT 1 OFFSET 1);

-- TASK NO.27 --
SELECT DISTINCT SAL
FROM EMPLOYEE
ORDER BY SAL ASC
LIMIT 1 OFFSET 2;

-- TASK NO.28 --
SELECT DISTINCT SAL
FROM EMPLOYEE
ORDER BY SAL DESC
LIMIT 1 OFFSET 3;

-- TASK NO.29 --
SELECT ENAME
FROM EMPLOYEE
WHERE SAL = (SELECT DISTINCT SAL FROM EMPLOYEE ORDER BY SAL DESC LIMIT 1 OFFSET 2);

-- TASK N0.30 --
SELECT EMP_NO
FROM EMPLOYEE
WHERE SAL = (SELECT MAX(SAL) FROM EMPLOYEE);

-- TASK NO.31 --
SELECT DEPRT_NO
FROM EMPLOYEE
WHERE SAL = (SELECT DISTINCT SAL FROM EMPLOYEE ORDER BY SAL DESC LIMIT 1 OFFSET 3);